# Updated: Force fresh deploy - using ES module
[build]
    command = "npm ci && node scripts/netlify-build.js"
  functions = "netlify/functions"
  publish = "dist/spa"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NODE_OPTIONS = "--max-old-space-size=4096"
  CI = "true"
  NODE_ENV = "production"
  NETLIFY = "true"
  # Supabase environment variables - required for database connection
  VITE_SUPABASE_URL = "https://yrsvksgkxjiogjuaeyvd.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlyc3Zrc2dreGppb2dqdWFleXZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MDMzMDMsImV4cCI6MjA2NzM3OTMwM30.-haPW80fiZMWYCm83TXvwZ2kHHBhcvhWAc6jPYdlUXM"
  # Additional serverless configuration
  AWS_LAMBDA_FUNCTION_NAME = "netlify-functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js", "pg", "bcryptjs", "jsonwebtoken", "serverless-http", "express", "cors", "multer"]
  included_files = ["shared/**/*", "server/**/*", "node_modules/@supabase/**/*"]

[functions.api]
  timeout = 30

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"
  status = 200
  force = true

# Static files redirects
[[redirects]]
  from = "/manifest.json"
  to = "/public/manifest.json"
  status = 200

[[redirects]]
  from = "/sw.js"
  to = "/public/sw.js"
  status = 200

[[redirects]]
  from = "/icon-192.png"
  to = "/public/icon.svg"
  status = 200

[[redirects]]
  from = "/icon-512.png"
  to = "/public/icon.svg"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables are configured directly in [build.environment] section above
