# Updated: Force fresh deploy - using ES module
[build]
    command = "npm ci && node scripts/netlify-build.js"
  functions = "netlify/functions"
  publish = "dist/spa"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NODE_OPTIONS = "--max-old-space-size=4096"
  CI = "true"
  NODE_ENV = "production"
  NETLIFY = "true"
  # Supabase environment variables - required for database connection
  VITE_SUPABASE_URL = "https://yrsvksgkxjiogjuaeyvd.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlyc3Zrc2dreGppb2dqdWFleXZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MDMzMDMsImV4cCI6MjA2NzM3OTMwM30.-haPW80fiZMWYCm83TXvwZ2kHHBhcvhWAc6jPYdlUXM"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js", "pg", "bcryptjs", "jsonwebtoken", "serverless-http", "express", "cors", "multer"]
  included_files = ["shared/**/*", "server/**/*", "node_modules/@supabase/**/*"]

[functions.api]
  timeout = 30

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api"
  to = "/.netlify/functions/api"
  status = 200
  force = true

# PWA files are served directly from the build output
# No redirects needed since they're in the root of dist/spa

# Offline page
[[redirects]]
  from = "/offline"
  to = "/index.html"
  status = 200

# Cache control headers for PWA
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "application/javascript"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables are configured directly in [build.environment] section above
